package com.yourorg.tokenisation.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.AccessLevel;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.UUID;

/**
 * JPA entity representing one issued token in the {@code token_vault} table.
 *
 * <p>A token vault record stores the encrypted form of a PAN together with all
 * cryptographic material needed to decrypt it later. The PAN itself is never stored
 * in plain text — only its AES-256-GCM ciphertext ({@code encryptedPan}), the
 * per-record IV ({@code iv}), the GCM authentication tag ({@code authTag}), and
 * the KEK-wrapped DEK ({@code encryptedDek}) are persisted.
 *
 * <p>{@code panHash} is an HMAC-SHA256 of the PAN used solely for de-duplication
 * of {@code RECURRING} tokens. It does not allow PAN recovery.
 *
 * <p>{@code recordVersion} is used for optimistic locking during key rotation
 * re-encryption. A rotation update that encounters a stale version is retried.
 */
@Entity
@Table(name = "token_vault")
@Getter
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class TokenVault {

    /** Primary key — assigned by the database using {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "token_id", updatable = false, nullable = false)
    private UUID tokenId;

    /**
     * The opaque surrogate value returned to the caller.
     * Formatted as a UUID string or Luhn-valid 16-digit string depending on configuration.
     */
    @Column(name = "token", nullable = false, unique = true, updatable = false)
    private String token;

    /**
     * AES-256-GCM ciphertext of the PAN, encrypted with the per-record DEK.
     * Length varies with PAN length. Updated during key rotation re-encryption.
     */
    @Column(name = "encrypted_pan", nullable = false)
    private byte[] encryptedPan;

    /**
     * 12-byte (96-bit) GCM initialisation vector, unique per encryption operation.
     * A fresh IV is generated by {@code SecureRandom} for every tokenise call.
     * Stored alongside the ciphertext and required for decryption.
     */
    @Column(name = "iv", nullable = false)
    private byte[] iv;

    /**
     * 16-byte (128-bit) GCM authentication tag appended by {@code Cipher.doFinal()}.
     * Verification of this tag during decryption detects any ciphertext tampering.
     * An {@code AEADBadTagException} on verification triggers a {@code TAMPER_ALERT} audit event.
     */
    @Column(name = "auth_tag", nullable = false)
    private byte[] authTag;

    /**
     * The per-record Data Encryption Key (DEK) wrapped by the active KEK.
     * Updated during key rotation to wrap the same DEK under the new KEK,
     * without re-encrypting the PAN ciphertext itself.
     */
    @Column(name = "encrypted_dek", nullable = false)
    private byte[] encryptedDek;

    /**
     * The key version whose KEK was used to wrap {@code encryptedDek}.
     * Used to look up the correct key material in the in-memory key ring during detokenisation.
     */
    @ManyToOne
    @JoinColumn(name = "key_version_id", nullable = false)
    private KeyVersion keyVersion;

    /**
     * HMAC-SHA256 of the PAN using a hashing secret separate from the KEK.
     * Used exclusively for de-duplication of {@code RECURRING} tokens.
     * Does not allow PAN recovery.
     */
    @Column(name = "pan_hash", nullable = false, updatable = false)
    private String panHash;

    /** Whether this token is for recurring billing (deterministic) or one-off payment (non-deterministic). */
    @Enumerated(EnumType.STRING)
    @Column(name = "token_type", nullable = false, updatable = false)
    private TokenType tokenType;

    /**
     * Last four digits of the PAN, stored in clear.
     * Not sensitive — used for display purposes (e.g. "Card ending in 1111").
     */
    @Column(name = "last_four", nullable = false, updatable = false, length = 4)
    private String lastFour;

    /**
     * Payment card scheme (e.g. {@code VISA}, {@code MC}, {@code AMEX}, {@code EFTPOS}).
     * Stored in clear for routing and display. May be {@code null} if unknown.
     */
    @Column(name = "card_scheme", updatable = false, length = 10)
    private String cardScheme;

    /** Card expiry month (1–12). May be {@code null} if not provided at tokenise time. */
    @Column(name = "expiry_month", updatable = false)
    private Short expiryMonth;

    /** Card expiry year (e.g. 2027). May be {@code null} if not provided at tokenise time. */
    @Column(name = "expiry_year", updatable = false)
    private Short expiryYear;

    /**
     * Scopes this token to a specific merchant.
     * Detokenisation requests from a different merchant are rejected with a 403.
     * Extracted from authenticated JWT claims — never sourced from the request body.
     */
    @Column(name = "merchant_id", updatable = false)
    private String merchantId;

    /** Timestamp when this token was created. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Optional expiry timestamp after which the token is considered inactive.
     * Detokenisation of an expired token returns 404.
     */
    @Column(name = "expires_at")
    private Instant expiresAt;

    /**
     * {@code false} when the token has been explicitly deactivated or has expired.
     * Inactive tokens cannot be detokenised.
     */
    @Column(name = "is_active", nullable = false)
    private boolean isActive;

    /**
     * Optimistic locking version counter, managed by JPA.
     * Incremented on every update. A stale {@code recordVersion} during rotation
     * causes an {@code OptimisticLockException}, which the rotation job retries.
     */
    @Version
    @Column(name = "record_version", nullable = false)
    private int recordVersion;

    /**
     * Constructs a new {@code TokenVault} record for a just-tokenised PAN.
     *
     * @param token          the opaque surrogate token value
     * @param encryptedPan   AES-256-GCM ciphertext of the PAN
     * @param iv             12-byte GCM IV used during PAN encryption
     * @param authTag        16-byte GCM authentication tag
     * @param encryptedDek   DEK wrapped by the active KEK
     * @param keyVersion     the key version whose KEK wrapped the DEK
     * @param panHash        HMAC-SHA256 of the PAN for de-duplication
     * @param tokenType      {@code RECURRING} or {@code ONE_TIME}
     * @param lastFour       last four digits of the PAN (stored in clear)
     * @param cardScheme     payment scheme (may be {@code null})
     * @param expiryMonth    card expiry month (may be {@code null})
     * @param expiryYear     card expiry year (may be {@code null})
     * @param merchantId     merchant scope (may be {@code null} for global tokens)
     * @param createdAt      creation timestamp
     * @param expiresAt      optional token expiry (may be {@code null})
     */
    @Builder
    public TokenVault(
            String token,
            byte[] encryptedPan,
            byte[] iv,
            byte[] authTag,
            byte[] encryptedDek,
            KeyVersion keyVersion,
            String panHash,
            TokenType tokenType,
            String lastFour,
            String cardScheme,
            Short expiryMonth,
            Short expiryYear,
            String merchantId,
            Instant createdAt,
            Instant expiresAt) {
        this.token = token;
        this.encryptedPan = encryptedPan.clone();
        this.iv = iv.clone();
        this.authTag = authTag.clone();
        this.encryptedDek = encryptedDek.clone();
        this.keyVersion = keyVersion;
        this.panHash = panHash;
        this.tokenType = tokenType;
        this.lastFour = lastFour;
        this.cardScheme = cardScheme;
        this.expiryMonth = expiryMonth;
        this.expiryYear = expiryYear;
        this.merchantId = merchantId;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.isActive = true;
        this.recordVersion = 1;
    }

    /**
     * Replaces the wrapped DEK and updates the associated key version after re-encryption.
     *
     * <p>Called by the rotation batch processor after a successful DEK re-wrap.
     * The PAN ciphertext and IV are unchanged — only the DEK wrapper changes.
     *
     * @param newEncryptedDek the DEK wrapped under the new KEK
     * @param newKeyVersion   the new key version whose KEK was used
     */
    public void reencryptDek(byte[] newEncryptedDek, KeyVersion newKeyVersion) {
        this.encryptedDek = newEncryptedDek.clone();
        this.keyVersion = newKeyVersion;
    }

    /**
     * Deactivates this token. Deactivated tokens cannot be detokenised.
     */
    public void deactivate() {
        this.isActive = false;
    }

    /**
     * Returns a defensive copy of the encrypted PAN bytes.
     *
     * @return copy of {@code encryptedPan}
     */
    public byte[] getEncryptedPan() {
        return encryptedPan.clone();
    }

    /**
     * Returns a defensive copy of the IV bytes.
     *
     * @return copy of {@code iv}
     */
    public byte[] getIv() {
        return iv.clone();
    }

    /**
     * Returns a defensive copy of the GCM authentication tag bytes.
     *
     * @return copy of {@code authTag}
     */
    public byte[] getAuthTag() {
        return authTag.clone();
    }

    /**
     * Returns a defensive copy of the encrypted DEK bytes.
     *
     * @return copy of {@code encryptedDek}
     */
    public byte[] getEncryptedDek() {
        return encryptedDek.clone();
    }
}
