package com.yourorg.tokenisation.crypto;

import org.springframework.stereotype.Component;

import javax.crypto.AEADBadTagException;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;
import java.util.Arrays;

/**
 * Provides AES-256-GCM authenticated encryption and decryption for PAN data.
 *
 * <p>Design decisions:
 * <ul>
 *   <li>A fresh 96-bit IV is generated by {@code SecureRandom} per encryption call.
 *       IV uniqueness is critical for GCM security — reusing an IV with the same key
 *       breaks confidentiality and authentication.
 *   <li>The DEK is supplied by the caller (from the in-memory ring); no per-record DEK
 *       is generated or wrapped here. The ring ensures the same DEK is used for all
 *       records on a given key version, and rotation re-encrypts PANs under a new DEK.
 *   <li>The GCM authentication tag is 128 bits (16 bytes) — NIST recommended maximum.
 * </ul>
 *
 * <p>This class is thread-safe: all state ({@code SecureRandom}, cipher instances) is
 * local to each method call. No fields are mutated after construction.
 */
@Component
public class AesGcmCipher {

    static final int GCM_IV_LENGTH_BYTES = 12;
    static final int GCM_TAG_LENGTH_BITS = 128;
    static final int GCM_TAG_LENGTH_BYTES = GCM_TAG_LENGTH_BITS / 8;
    static final int AES_256_KEY_LENGTH_BYTES = 32;

    private static final String AES_GCM_ALGORITHM = "AES/GCM/NoPadding";
    private static final String AES_KEY_ALGORITHM = "AES";

    private final SecureRandom secureRandom;

    public AesGcmCipher() {
        this.secureRandom = new SecureRandom();
    }

    /**
     * Encrypts PAN bytes using AES-256-GCM with the supplied DEK.
     *
     * <p>A fresh random IV is generated for each call. The DEK is provided by the caller
     * (retrieved from the in-memory ring) and must be zeroed by the caller after this call.
     *
     * @param panBytes the raw PAN as bytes; must not be null or empty
     * @param dek      the 32-byte Data Encryption Key; must be exactly 32 bytes
     * @return an {@link EncryptResult} containing ciphertext, IV, and auth tag — safe to persist
     * @throws IllegalArgumentException if {@code panBytes} is null/empty or {@code dek} is not 32 bytes
     * @throws EncryptionException      if the JCE operation fails
     */
    public EncryptResult encrypt(byte[] panBytes, byte[] dek) {
        validatePanBytes(panBytes);
        validateDek(dek);

        byte[] iv = generateIv();
        byte[] ciphertextWithTag = encryptWithKey(panBytes, dek, iv);
        byte[] ciphertext = extractCiphertext(ciphertextWithTag);
        byte[] authTag = extractAuthTag(ciphertextWithTag);
        return new EncryptResult(ciphertext, iv, authTag);
    }

    /**
     * Decrypts PAN bytes using AES-256-GCM with the supplied DEK.
     *
     * <p>The GCM authentication tag is verified implicitly by the JCE provider during
     * {@code doFinal} — any ciphertext modification causes an {@code AEADBadTagException},
     * rethrown as {@code EncryptionException} with a tamper-indicating message.
     *
     * @param ciphertext the AES-256-GCM ciphertext; must not be null
     * @param iv         the 12-byte GCM IV used during encryption; must be exactly 12 bytes
     * @param authTag    the 16-byte GCM authentication tag; must be exactly 16 bytes
     * @param dek        the 32-byte Data Encryption Key; must be exactly 32 bytes
     * @return the decrypted PAN bytes
     * @throws IllegalArgumentException if any argument is null or has an invalid length
     * @throws EncryptionException      if the GCM auth tag fails (tamper detected) or the JCE operation fails
     */
    public byte[] decrypt(byte[] ciphertext, byte[] iv, byte[] authTag, byte[] dek) {
        validateIv(iv);
        validateAuthTag(authTag);
        validateDek(dek);

        byte[] ciphertextWithTag = joinCiphertextAndTag(ciphertext, authTag);
        return decryptRaw(ciphertextWithTag, iv, dek);
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    private byte[] generateIv() {
        byte[] iv = new byte[GCM_IV_LENGTH_BYTES];
        secureRandom.nextBytes(iv);
        return iv;
    }

    private byte[] encryptWithKey(byte[] plaintext, byte[] key, byte[] iv) {
        try {
            SecretKeySpec keySpec = new SecretKeySpec(key, AES_KEY_ALGORITHM);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            Cipher cipher = Cipher.getInstance(AES_GCM_ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, keySpec, gcmSpec);
            return cipher.doFinal(plaintext);
        } catch (Exception encryptionFailure) {
            throw new EncryptionException("AES-GCM encryption failed", encryptionFailure);
        }
    }

    private byte[] decryptRaw(byte[] ciphertextWithTag, byte[] iv, byte[] key) {
        try {
            SecretKeySpec keySpec = new SecretKeySpec(key, AES_KEY_ALGORITHM);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            Cipher cipher = Cipher.getInstance(AES_GCM_ALGORITHM);
            cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmSpec);
            return cipher.doFinal(ciphertextWithTag);
        } catch (AEADBadTagException tamperException) {
            throw new EncryptionException("GCM authentication tag verification failed — ciphertext may have been tampered with", tamperException);
        } catch (Exception decryptionFailure) {
            throw new EncryptionException("AES-GCM decryption failed", decryptionFailure);
        }
    }

    private byte[] extractCiphertext(byte[] ciphertextWithTag) {
        int ciphertextLength = ciphertextWithTag.length - GCM_TAG_LENGTH_BYTES;
        return Arrays.copyOfRange(ciphertextWithTag, 0, ciphertextLength);
    }

    private byte[] extractAuthTag(byte[] ciphertextWithTag) {
        int tagOffset = ciphertextWithTag.length - GCM_TAG_LENGTH_BYTES;
        return Arrays.copyOfRange(ciphertextWithTag, tagOffset, ciphertextWithTag.length);
    }

    private byte[] joinCiphertextAndTag(byte[] ciphertext, byte[] authTag) {
        byte[] combined = new byte[ciphertext.length + authTag.length];
        System.arraycopy(ciphertext, 0, combined, 0, ciphertext.length);
        System.arraycopy(authTag, 0, combined, ciphertext.length, authTag.length);
        return combined;
    }

    private void validatePanBytes(byte[] panBytes) {
        if (panBytes == null || panBytes.length == 0) {
            throw new IllegalArgumentException("PAN bytes must not be null or empty");
        }
    }

    private void validateDek(byte[] dek) {
        if (dek == null || dek.length != AES_256_KEY_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "DEK must be exactly 32 bytes (AES-256); got: " + (dek == null ? "null" : dek.length));
        }
    }

    private void validateIv(byte[] iv) {
        if (iv == null || iv.length != GCM_IV_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "IV must be exactly 12 bytes; got: " + (iv == null ? "null" : iv.length));
        }
    }

    private void validateAuthTag(byte[] authTag) {
        if (authTag == null || authTag.length != GCM_TAG_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "Auth tag must be exactly 16 bytes; got: " + (authTag == null ? "null" : authTag.length));
        }
    }
}
