package com.yourorg.tokenisation.crypto;

import org.springframework.stereotype.Component;

import javax.crypto.AEADBadTagException;
import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.security.SecureRandom;
import java.util.Arrays;

/**
 * Provides AES-256-GCM authenticated encryption and decryption for PAN data,
 * and AES-KW (key wrap) operations for Data Encryption Keys (DEKs).
 *
 * <p>Design decisions:
 * <ul>
 *   <li>A fresh 96-bit IV is generated by {@code SecureRandom} per encryption call.
 *       IV uniqueness is critical for GCM security — reusing an IV with the same key
 *       breaks confidentiality and authentication.
 *   <li>DEKs are generated locally using {@code SecureRandom} — no KMS call per tokenisation.
 *       The DEK is then wrapped by the in-memory KEK (AES-GCM wrap) before storage.
 *   <li>All DEK byte arrays are zeroed in {@code finally} blocks immediately after use,
 *       regardless of whether the operation succeeds or fails.
 *   <li>The GCM authentication tag is 128 bits (16 bytes) — NIST recommended maximum.
 * </ul>
 *
 * <p>This class is thread-safe: all state ({@code SecureRandom}, cipher instances) is
 * local to each method call. No fields are mutated after construction.
 */
@Component
public class AesGcmCipher {

    static final int GCM_IV_LENGTH_BYTES = 12;
    static final int GCM_TAG_LENGTH_BITS = 128;
    static final int GCM_TAG_LENGTH_BYTES = GCM_TAG_LENGTH_BITS / 8;
    static final int AES_256_KEY_LENGTH_BYTES = 32;

    private static final String AES_GCM_ALGORITHM = "AES/GCM/NoPadding";
    private static final String AES_KEY_ALGORITHM = "AES";

    private final SecureRandom secureRandom;

    /**
     * Constructs an {@code AesGcmCipher} using a shared {@code SecureRandom} instance.
     *
     * <p>{@code SecureRandom} is thread-safe and expensive to construct. The instance
     * is shared across calls — individual IV and DEK generation calls read from it
     * concurrently without corruption.
     */
    public AesGcmCipher() {
        this.secureRandom = new SecureRandom();
    }

    /**
     * Encrypts PAN bytes using AES-256-GCM with a freshly generated DEK.
     *
     * <p>A new random DEK and IV are generated for each call. The DEK is wrapped by
     * the provided KEK using AES-GCM before being included in the result. The plaintext
     * DEK is zeroed from memory in a {@code finally} block regardless of outcome.
     *
     * @param panBytes the raw PAN as bytes (UTF-8 encoded digit string); must not be null or empty
     * @param kek      the Key Encryption Key used to wrap the DEK; must be exactly 32 bytes (AES-256)
     * @return an {@link EncryptResult} containing ciphertext, IV, auth tag, and the wrapped DEK —
     *         all fields are safe to persist
     * @throws IllegalArgumentException if {@code panBytes} is null/empty or {@code kek} is not 32 bytes
     * @throws EncryptionException      if the JCE operation fails
     */
    public EncryptResult encrypt(byte[] panBytes, byte[] kek) {
        validatePanBytes(panBytes);
        validateKek(kek);

        byte[] dek = generateDek();
        try {
            byte[] iv = generateIv();
            byte[] ciphertextWithTag = encryptWithDek(panBytes, dek, iv);
            byte[] ciphertext = extractCiphertext(ciphertextWithTag);
            byte[] authTag = extractAuthTag(ciphertextWithTag);
            byte[] encryptedDek = wrapDek(dek, kek);
            return new EncryptResult(ciphertext, iv, authTag, encryptedDek);
        } finally {
            // DEK must not persist in memory beyond this method call
            Arrays.fill(dek, (byte) 0);
        }
    }

    /**
     * Decrypts PAN bytes using AES-256-GCM.
     *
     * <p>The DEK is first unwrapped from the stored encrypted form using the KEK,
     * then used to decrypt the ciphertext. The GCM authentication tag is verified
     * implicitly by the JCE provider during {@code doFinal} — any ciphertext
     * modification causes an {@code AEADBadTagException}, which is rethrown as
     * {@code EncryptionException} with a tamper-indicating message.
     *
     * <p>The DEK is zeroed from memory in a {@code finally} block regardless of outcome.
     *
     * @param ciphertext   the AES-256-GCM ciphertext of the PAN; must not be null
     * @param iv           the 12-byte GCM IV used during encryption; must be exactly 12 bytes
     * @param authTag      the 16-byte GCM authentication tag; must be exactly 16 bytes
     * @param encryptedDek the KEK-wrapped DEK from storage; must not be null
     * @param kek          the Key Encryption Key used to unwrap the DEK; must be exactly 32 bytes
     * @return the decrypted PAN bytes
     * @throws IllegalArgumentException if any argument is null or has an invalid length
     * @throws EncryptionException      if the GCM auth tag fails (tamper detected) or the JCE operation fails
     */
    public byte[] decrypt(byte[] ciphertext, byte[] iv, byte[] authTag, byte[] encryptedDek, byte[] kek) {
        validateIv(iv);
        validateAuthTag(authTag);
        validateKek(kek);

        byte[] dek = unwrapDek(encryptedDek, kek);
        try {
            return decryptWithDek(ciphertext, iv, authTag, dek);
        } finally {
            Arrays.fill(dek, (byte) 0);
        }
    }

    /**
     * Wraps a DEK using AES-256-GCM with the provided KEK.
     *
     * <p>Format: {@code [12-byte IV][AES-GCM ciphertext of DEK][16-byte auth tag]}.
     * A fresh IV is generated per call so that two wraps of the same DEK produce different blobs.
     *
     * @param plaintextDek the 32-byte DEK to wrap; must not be null; must be exactly 32 bytes
     * @param kek          the Key Encryption Key; must be exactly 32 bytes
     * @return IV-prefixed GCM ciphertext of the DEK (60 bytes total: 12 + 32 + 16)
     * @throws IllegalArgumentException if either argument is null or has incorrect length
     * @throws EncryptionException      if the JCE operation fails
     */
    public byte[] wrapDek(byte[] plaintextDek, byte[] kek) {
        if (plaintextDek == null || plaintextDek.length != AES_256_KEY_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "Plaintext DEK must be exactly 32 bytes; got: " + (plaintextDek == null ? "null" : plaintextDek.length));
        }
        validateKek(kek);

        byte[] iv = generateIv();
        byte[] wrappedWithTag = encryptWithDek(plaintextDek, kek, iv);
        return prependIv(iv, wrappedWithTag);
    }

    /**
     * Unwraps a DEK that was wrapped by {@link #wrapDek}.
     *
     * <p>The caller is responsible for zeroing the returned array after use.
     *
     * @param ivPrefixedWrappedDek IV-prefixed GCM ciphertext as produced by {@code wrapDek};
     *                              must not be null; must be at least 28 bytes (12 IV + 16 tag)
     * @param kek                  the Key Encryption Key used during the original wrap; must be 32 bytes
     * @return the plaintext 32-byte DEK — caller must zero after use
     * @throws IllegalArgumentException if arguments are null or too short
     * @throws EncryptionException      if the GCM auth tag fails or decryption fails
     */
    public byte[] unwrapDek(byte[] ivPrefixedWrappedDek, byte[] kek) {
        if (ivPrefixedWrappedDek == null || ivPrefixedWrappedDek.length < GCM_IV_LENGTH_BYTES + GCM_TAG_LENGTH_BYTES) {
            throw new IllegalArgumentException("Wrapped DEK is null or too short to contain a valid IV and tag");
        }
        validateKek(kek);

        byte[] iv = Arrays.copyOfRange(ivPrefixedWrappedDek, 0, GCM_IV_LENGTH_BYTES);
        byte[] ciphertextWithTag = Arrays.copyOfRange(ivPrefixedWrappedDek, GCM_IV_LENGTH_BYTES, ivPrefixedWrappedDek.length);
        return decryptRaw(ciphertextWithTag, iv, kek);
    }

    // ── Private helpers ──────────────────────────────────────────────────────

    private byte[] generateDek() {
        byte[] dek = new byte[AES_256_KEY_LENGTH_BYTES];
        secureRandom.nextBytes(dek);
        return dek;
    }

    private byte[] generateIv() {
        byte[] iv = new byte[GCM_IV_LENGTH_BYTES];
        secureRandom.nextBytes(iv);
        return iv;
    }

    private byte[] encryptWithDek(byte[] plaintext, byte[] key, byte[] iv) {
        try {
            SecretKeySpec keySpec = new SecretKeySpec(key, AES_KEY_ALGORITHM);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            Cipher cipher = Cipher.getInstance(AES_GCM_ALGORITHM);
            cipher.init(Cipher.ENCRYPT_MODE, keySpec, gcmSpec);
            // GCM NoPadding: doFinal appends the auth tag directly after the ciphertext
            return cipher.doFinal(plaintext);
        } catch (Exception encryptionFailure) {
            throw new EncryptionException("AES-GCM encryption failed", encryptionFailure);
        }
    }

    private byte[] decryptWithDek(byte[] ciphertext, byte[] iv, byte[] authTag, byte[] key) {
        // Reconstitute the GCM ciphertext+tag blob that JCE expects
        byte[] ciphertextWithTag = joinCiphertextAndTag(ciphertext, authTag);
        return decryptRaw(ciphertextWithTag, iv, key);
    }

    private byte[] decryptRaw(byte[] ciphertextWithTag, byte[] iv, byte[] key) {
        try {
            SecretKeySpec keySpec = new SecretKeySpec(key, AES_KEY_ALGORITHM);
            GCMParameterSpec gcmSpec = new GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv);
            Cipher cipher = Cipher.getInstance(AES_GCM_ALGORITHM);
            cipher.init(Cipher.DECRYPT_MODE, keySpec, gcmSpec);
            // AEADBadTagException is thrown by doFinal if the auth tag does not match —
            // this indicates ciphertext or IV tampering
            return cipher.doFinal(ciphertextWithTag);
        } catch (AEADBadTagException tamperException) {
            throw new EncryptionException("GCM authentication tag verification failed — ciphertext may have been tampered with", tamperException);
        } catch (Exception decryptionFailure) {
            throw new EncryptionException("AES-GCM decryption failed", decryptionFailure);
        }
    }

    private byte[] extractCiphertext(byte[] ciphertextWithTag) {
        int ciphertextLength = ciphertextWithTag.length - GCM_TAG_LENGTH_BYTES;
        return Arrays.copyOfRange(ciphertextWithTag, 0, ciphertextLength);
    }

    private byte[] extractAuthTag(byte[] ciphertextWithTag) {
        int tagOffset = ciphertextWithTag.length - GCM_TAG_LENGTH_BYTES;
        return Arrays.copyOfRange(ciphertextWithTag, tagOffset, ciphertextWithTag.length);
    }

    private byte[] joinCiphertextAndTag(byte[] ciphertext, byte[] authTag) {
        byte[] combined = new byte[ciphertext.length + authTag.length];
        System.arraycopy(ciphertext, 0, combined, 0, ciphertext.length);
        System.arraycopy(authTag, 0, combined, ciphertext.length, authTag.length);
        return combined;
    }

    private byte[] prependIv(byte[] iv, byte[] payload) {
        byte[] combined = new byte[iv.length + payload.length];
        System.arraycopy(iv, 0, combined, 0, iv.length);
        System.arraycopy(payload, 0, combined, iv.length, payload.length);
        return combined;
    }

    private void validatePanBytes(byte[] panBytes) {
        if (panBytes == null || panBytes.length == 0) {
            throw new IllegalArgumentException("PAN bytes must not be null or empty");
        }
    }

    private void validateKek(byte[] kek) {
        if (kek == null || kek.length != AES_256_KEY_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "KEK must be exactly 32 bytes (AES-256); got: " + (kek == null ? "null" : kek.length));
        }
    }

    private void validateIv(byte[] iv) {
        if (iv == null || iv.length != GCM_IV_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "IV must be exactly 12 bytes; got: " + (iv == null ? "null" : iv.length));
        }
    }

    private void validateAuthTag(byte[] authTag) {
        if (authTag == null || authTag.length != GCM_TAG_LENGTH_BYTES) {
            throw new IllegalArgumentException(
                    "Auth tag must be exactly 16 bytes; got: " + (authTag == null ? "null" : authTag.length));
        }
    }
}
